INSERT INTO products (
    id,
    name,
    description,
    price,
    currency,
    stock_quantity,
    image_url,
    category_id,
    category_name,
    is_active,
    created_at,
    updated_at
) VALUES
    (
        4,
        'Laptop Pro',
        'High-performance laptop with 16GB RAM and 512GB SSD',
        1299.99,
        'EUR',
        50,
        'https://images.stockcake.com/public/1/f/e/1fec4b0a-7d31-43fe-a6c4-9fa1ac194d57/laptop-on-desk-stockcake.jpg',
        1,
        'Electronics',
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        'Smartphone X',
        'Latest smartphone with 6.5-inch display and 128GB storage',
        899.99,
        'EUR',
        100,
        'https://images.stockcake.com/public/4/1/f/41ff3157-5cf5-4fb6-894e-ca05ea4f8da0_large/smartphone-interactive-display-stockcake.jpg',
        1,
        'Electronics',
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        'Noise-Cancelling Headphones',
        'Premium wireless headphones with active noise cancellation',
        249.99,
        'EUR',
        75,
        'https://images.stockcake.com/public/b/d/e/bde9ffd3-6b54-4add-860d-116dcfe1efa6_large/neon-floating-headphones-stockcake.jpg',
        1,
        'Electronics',
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        'Slim Fit Jeans',
        'Classic slim fit jeans in dark blue',
        49.99,
        'EUR',
        150,
        'https://images.stockcake.com/public/0/4/f/04ffffab-9fef-4bd5-8494-980490bd840a_large/hanging-denim-jeans-stockcake.jpg',
        2,
        'Clothing',
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    description = VALUES(description),
    price = VALUES(price),
    currency = VALUES(currency),
    stock_quantity = VALUES(stock_quantity),
    image_url = VALUES(image_url),
    category_id = VALUES(category_id),
    category_name = VALUES(category_name),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at);
